// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

// These functions are ignored because they are not marked as `pub`: `extract_course_info`, `extract_download_path`, `extract_hidden_input_value`, `extract_lectures`, `extract_path_from_vtop_download`, `parse_erp_id_from_onclick`

/// Parses the courses dropdown from the course page HTML response
Future<CoursesResponse> parseCoursesForCoursePage({required String html}) =>
    RustLib.instance.api
        .crateApiVtopParaserCoursePageParserParseCoursesForCoursePage(
          html: html,
        );

/// Parses the slots and class entries from the slot selection response
Future<SlotsResponse> parseSlotsForCoursePage({
  required String html,
  required String semesterId,
}) => RustLib.instance.api
    .crateApiVtopParaserCoursePageParserParseSlotsForCoursePage(
      html: html,
      semesterId: semesterId,
    );

/// Parses the detailed course page with all lectures and materials
Future<CoursePageDetail> parseCourseDetailPage({required String html}) =>
    RustLib.instance.api
        .crateApiVtopParaserCoursePageParserParseCourseDetailPage(html: html);
