// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

// These functions are ignored because they are not marked as `pub`: `clean_grade_range_text`, `extract_course_id`, `extract_text`, `looks_like_grade_range`, `now_unix`

Future<GradeViewData> parseGradeView({
  required String html,
  required String sem,
}) => RustLib.instance.api.crateApiVtopParaserParsegradesParseGradeView(
  html: html,
  sem: sem,
);

Future<GradeDetailsData> parseGradeViewDetails({
  required String html,
  required String sem,
  required String courseId,
}) => RustLib.instance.api.crateApiVtopParaserParsegradesParseGradeViewDetails(
  html: html,
  sem: sem,
  courseId: courseId,
);
