// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/logging.dart';
import 'api/simple.dart';
import 'api/vtop/paraser/course_page_parser.dart';
import 'api/vtop/paraser/parseattn.dart';
import 'api/vtop/paraser/parsegradehistory.dart';
import 'api/vtop/paraser/parsegrades.dart';
import 'api/vtop/paraser/parsemarks.dart';
import 'api/vtop/paraser/parsesched.dart';
import 'api/vtop/paraser/parsett.dart';
import 'api/vtop/session_manager.dart';
import 'api/vtop/types.dart';
import 'api/vtop/vtop_client.dart';
import 'api/vtop/vtop_config.dart';
import 'api/vtop/vtop_errors.dart';
import 'api/vtop_get_client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:meta/meta.dart' as meta;

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcJarPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SessionManagerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopClientBuilderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultAttendanceDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultCoursePageDetailPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultCoursesResponsePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultExamScheduleDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultFullAttendanceDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultGradeDetailsDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultGradeHistoryDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultGradeViewDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultMarksDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultSemesterDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultSlotsResponsePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultTimetableDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopResultVecU8Ptr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcJar
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  VtopClientBuilder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    dynamic raw,
  );

  @protected
  VtopResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    dynamic raw,
  );

  @protected
  VtopResultAttendanceData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    dynamic raw,
  );

  @protected
  VtopResultCoursePageDetail
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    dynamic raw,
  );

  @protected
  VtopResultCoursesResponse
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    dynamic raw,
  );

  @protected
  VtopResultExamScheduleData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    dynamic raw,
  );

  @protected
  VtopResultFullAttendanceData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    dynamic raw,
  );

  @protected
  VtopResultGradeDetailsData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    dynamic raw,
  );

  @protected
  VtopResultGradeHistoryData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    dynamic raw,
  );

  @protected
  VtopResultGradeViewData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    dynamic raw,
  );

  @protected
  VtopResultMarksData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    dynamic raw,
  );

  @protected
  VtopResultSemesterData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    dynamic raw,
  );

  @protected
  VtopResultSlotsResponse
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    dynamic raw,
  );

  @protected
  VtopResultTimetableData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    dynamic raw,
  );

  @protected
  VtopResultVecU8
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  ArcJar
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  VtopClientBuilder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    dynamic raw,
  );

  @protected
  VtopResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    dynamic raw,
  );

  @protected
  VtopResultAttendanceData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    dynamic raw,
  );

  @protected
  VtopResultCoursePageDetail
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    dynamic raw,
  );

  @protected
  VtopResultCoursesResponse
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    dynamic raw,
  );

  @protected
  VtopResultExamScheduleData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    dynamic raw,
  );

  @protected
  VtopResultFullAttendanceData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    dynamic raw,
  );

  @protected
  VtopResultGradeDetailsData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    dynamic raw,
  );

  @protected
  VtopResultGradeHistoryData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    dynamic raw,
  );

  @protected
  VtopResultGradeViewData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    dynamic raw,
  );

  @protected
  VtopResultMarksData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    dynamic raw,
  );

  @protected
  VtopResultSemesterData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    dynamic raw,
  );

  @protected
  VtopResultSlotsResponse
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    dynamic raw,
  );

  @protected
  VtopResultTimetableData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    dynamic raw,
  );

  @protected
  VtopResultVecU8
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeLogEntry> dco_decode_StreamSink_bridge_log_entry_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AttendanceData dco_decode_attendance_data(dynamic raw);

  @protected
  AttendanceRecord dco_decode_attendance_record(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  VtopConfig dco_decode_box_autoadd_vtop_config(dynamic raw);

  @protected
  BridgeLogEntry dco_decode_bridge_log_entry(dynamic raw);

  @protected
  BridgeLogLevel dco_decode_bridge_log_level(dynamic raw);

  @protected
  CourseClassEntry dco_decode_course_class_entry(dynamic raw);

  @protected
  CourseInfo dco_decode_course_info(dynamic raw);

  @protected
  CourseOption dco_decode_course_option(dynamic raw);

  @protected
  CoursePageDetail dco_decode_course_page_detail(dynamic raw);

  @protected
  CoursesResponse dco_decode_courses_response(dynamic raw);

  @protected
  ExamScheduleData dco_decode_exam_schedule_data(dynamic raw);

  @protected
  ExamScheduleRecord dco_decode_exam_schedule_record(dynamic raw);

  @protected
  FullAttendanceData dco_decode_full_attendance_data(dynamic raw);

  @protected
  FullAttendanceRecord dco_decode_full_attendance_record(dynamic raw);

  @protected
  GradeCourseRecord dco_decode_grade_course_record(dynamic raw);

  @protected
  GradeDetailMark dco_decode_grade_detail_mark(dynamic raw);

  @protected
  GradeDetailsData dco_decode_grade_details_data(dynamic raw);

  @protected
  GradeHistoryAttempt dco_decode_grade_history_attempt(dynamic raw);

  @protected
  GradeHistoryCgpa dco_decode_grade_history_cgpa(dynamic raw);

  @protected
  GradeHistoryData dco_decode_grade_history_data(dynamic raw);

  @protected
  GradeHistoryRecord dco_decode_grade_history_record(dynamic raw);

  @protected
  GradeHistoryStudentInfo dco_decode_grade_history_student_info(dynamic raw);

  @protected
  GradeRange dco_decode_grade_range(dynamic raw);

  @protected
  GradeViewData dco_decode_grade_view_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LectureEntry dco_decode_lecture_entry(dynamic raw);

  @protected
  List<AttendanceRecord> dco_decode_list_attendance_record(dynamic raw);

  @protected
  List<CourseClassEntry> dco_decode_list_course_class_entry(dynamic raw);

  @protected
  List<CourseOption> dco_decode_list_course_option(dynamic raw);

  @protected
  List<ExamScheduleRecord> dco_decode_list_exam_schedule_record(dynamic raw);

  @protected
  List<FullAttendanceRecord> dco_decode_list_full_attendance_record(
    dynamic raw,
  );

  @protected
  List<GradeCourseRecord> dco_decode_list_grade_course_record(dynamic raw);

  @protected
  List<GradeDetailMark> dco_decode_list_grade_detail_mark(dynamic raw);

  @protected
  List<GradeHistoryAttempt> dco_decode_list_grade_history_attempt(dynamic raw);

  @protected
  List<GradeHistoryRecord> dco_decode_list_grade_history_record(dynamic raw);

  @protected
  List<GradeRange> dco_decode_list_grade_range(dynamic raw);

  @protected
  List<LectureEntry> dco_decode_list_lecture_entry(dynamic raw);

  @protected
  List<MarksRecord> dco_decode_list_marks_record(dynamic raw);

  @protected
  List<MarksRecordEach> dco_decode_list_marks_record_each(dynamic raw);

  @protected
  List<PerExamScheduleRecord> dco_decode_list_per_exam_schedule_record(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReferenceMaterial> dco_decode_list_reference_material(dynamic raw);

  @protected
  List<SemesterInfo> dco_decode_list_semester_info(dynamic raw);

  @protected
  List<SlotOption> dco_decode_list_slot_option(dynamic raw);

  @protected
  List<TimetableSlot> dco_decode_list_timetable_slot(dynamic raw);

  @protected
  MarksData dco_decode_marks_data(dynamic raw);

  @protected
  MarksRecord dco_decode_marks_record(dynamic raw);

  @protected
  MarksRecordEach dco_decode_marks_record_each(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PerExamScheduleRecord dco_decode_per_exam_schedule_record(dynamic raw);

  @protected
  ReferenceMaterial dco_decode_reference_material(dynamic raw);

  @protected
  SemesterData dco_decode_semester_data(dynamic raw);

  @protected
  SemesterInfo dco_decode_semester_info(dynamic raw);

  @protected
  SlotOption dco_decode_slot_option(dynamic raw);

  @protected
  SlotsResponse dco_decode_slots_response(dynamic raw);

  @protected
  TimetableData dco_decode_timetable_data(dynamic raw);

  @protected
  TimetableSlot dco_decode_timetable_slot(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VtopConfig dco_decode_vtop_config(dynamic raw);

  @protected
  VtopError dco_decode_vtop_error(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcJar
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  VtopClientBuilder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    SseDeserializer deserializer,
  );

  @protected
  VtopResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultAttendanceData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultCoursePageDetail
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultCoursesResponse
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultExamScheduleData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultFullAttendanceData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultGradeDetailsData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultGradeHistoryData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultGradeViewData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultMarksData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultSemesterData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultSlotsResponse
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultTimetableData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultVecU8
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  ArcJar
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  VtopClientBuilder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    SseDeserializer deserializer,
  );

  @protected
  VtopResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultAttendanceData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultCoursePageDetail
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultCoursesResponse
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultExamScheduleData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultFullAttendanceData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultGradeDetailsData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultGradeHistoryData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultGradeViewData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultMarksData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultSemesterData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultSlotsResponse
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultTimetableData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    SseDeserializer deserializer,
  );

  @protected
  VtopResultVecU8
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeLogEntry> sse_decode_StreamSink_bridge_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AttendanceData sse_decode_attendance_data(SseDeserializer deserializer);

  @protected
  AttendanceRecord sse_decode_attendance_record(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  VtopConfig sse_decode_box_autoadd_vtop_config(SseDeserializer deserializer);

  @protected
  BridgeLogEntry sse_decode_bridge_log_entry(SseDeserializer deserializer);

  @protected
  BridgeLogLevel sse_decode_bridge_log_level(SseDeserializer deserializer);

  @protected
  CourseClassEntry sse_decode_course_class_entry(SseDeserializer deserializer);

  @protected
  CourseInfo sse_decode_course_info(SseDeserializer deserializer);

  @protected
  CourseOption sse_decode_course_option(SseDeserializer deserializer);

  @protected
  CoursePageDetail sse_decode_course_page_detail(SseDeserializer deserializer);

  @protected
  CoursesResponse sse_decode_courses_response(SseDeserializer deserializer);

  @protected
  ExamScheduleData sse_decode_exam_schedule_data(SseDeserializer deserializer);

  @protected
  ExamScheduleRecord sse_decode_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  FullAttendanceData sse_decode_full_attendance_data(
    SseDeserializer deserializer,
  );

  @protected
  FullAttendanceRecord sse_decode_full_attendance_record(
    SseDeserializer deserializer,
  );

  @protected
  GradeCourseRecord sse_decode_grade_course_record(
    SseDeserializer deserializer,
  );

  @protected
  GradeDetailMark sse_decode_grade_detail_mark(SseDeserializer deserializer);

  @protected
  GradeDetailsData sse_decode_grade_details_data(SseDeserializer deserializer);

  @protected
  GradeHistoryAttempt sse_decode_grade_history_attempt(
    SseDeserializer deserializer,
  );

  @protected
  GradeHistoryCgpa sse_decode_grade_history_cgpa(SseDeserializer deserializer);

  @protected
  GradeHistoryData sse_decode_grade_history_data(SseDeserializer deserializer);

  @protected
  GradeHistoryRecord sse_decode_grade_history_record(
    SseDeserializer deserializer,
  );

  @protected
  GradeHistoryStudentInfo sse_decode_grade_history_student_info(
    SseDeserializer deserializer,
  );

  @protected
  GradeRange sse_decode_grade_range(SseDeserializer deserializer);

  @protected
  GradeViewData sse_decode_grade_view_data(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LectureEntry sse_decode_lecture_entry(SseDeserializer deserializer);

  @protected
  List<AttendanceRecord> sse_decode_list_attendance_record(
    SseDeserializer deserializer,
  );

  @protected
  List<CourseClassEntry> sse_decode_list_course_class_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<CourseOption> sse_decode_list_course_option(
    SseDeserializer deserializer,
  );

  @protected
  List<ExamScheduleRecord> sse_decode_list_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  List<FullAttendanceRecord> sse_decode_list_full_attendance_record(
    SseDeserializer deserializer,
  );

  @protected
  List<GradeCourseRecord> sse_decode_list_grade_course_record(
    SseDeserializer deserializer,
  );

  @protected
  List<GradeDetailMark> sse_decode_list_grade_detail_mark(
    SseDeserializer deserializer,
  );

  @protected
  List<GradeHistoryAttempt> sse_decode_list_grade_history_attempt(
    SseDeserializer deserializer,
  );

  @protected
  List<GradeHistoryRecord> sse_decode_list_grade_history_record(
    SseDeserializer deserializer,
  );

  @protected
  List<GradeRange> sse_decode_list_grade_range(SseDeserializer deserializer);

  @protected
  List<LectureEntry> sse_decode_list_lecture_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<MarksRecord> sse_decode_list_marks_record(SseDeserializer deserializer);

  @protected
  List<MarksRecordEach> sse_decode_list_marks_record_each(
    SseDeserializer deserializer,
  );

  @protected
  List<PerExamScheduleRecord> sse_decode_list_per_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReferenceMaterial> sse_decode_list_reference_material(
    SseDeserializer deserializer,
  );

  @protected
  List<SemesterInfo> sse_decode_list_semester_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SlotOption> sse_decode_list_slot_option(SseDeserializer deserializer);

  @protected
  List<TimetableSlot> sse_decode_list_timetable_slot(
    SseDeserializer deserializer,
  );

  @protected
  MarksData sse_decode_marks_data(SseDeserializer deserializer);

  @protected
  MarksRecord sse_decode_marks_record(SseDeserializer deserializer);

  @protected
  MarksRecordEach sse_decode_marks_record_each(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PerExamScheduleRecord sse_decode_per_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceMaterial sse_decode_reference_material(SseDeserializer deserializer);

  @protected
  SemesterData sse_decode_semester_data(SseDeserializer deserializer);

  @protected
  SemesterInfo sse_decode_semester_info(SseDeserializer deserializer);

  @protected
  SlotOption sse_decode_slot_option(SseDeserializer deserializer);

  @protected
  SlotsResponse sse_decode_slots_response(SseDeserializer deserializer);

  @protected
  TimetableData sse_decode_timetable_data(SseDeserializer deserializer);

  @protected
  TimetableSlot sse_decode_timetable_slot(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VtopConfig sse_decode_vtop_config(SseDeserializer deserializer);

  @protected
  VtopError sse_decode_vtop_error(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    ArcJar self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    VtopClientBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    VtopResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    VtopResultAttendanceData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    VtopResultCoursePageDetail self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    VtopResultCoursesResponse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    VtopResultExamScheduleData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    VtopResultFullAttendanceData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    VtopResultGradeDetailsData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    VtopResultGradeHistoryData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    VtopResultGradeViewData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    VtopResultMarksData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    VtopResultSemesterData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    VtopResultSlotsResponse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    VtopResultTimetableData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    VtopResultVecU8 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    ArcJar self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    VtopClientBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    VtopResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    VtopResultAttendanceData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    VtopResultCoursePageDetail self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    VtopResultCoursesResponse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    VtopResultExamScheduleData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    VtopResultFullAttendanceData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    VtopResultGradeDetailsData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    VtopResultGradeHistoryData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    VtopResultGradeViewData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    VtopResultMarksData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    VtopResultSemesterData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    VtopResultSlotsResponse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    VtopResultTimetableData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    VtopResultVecU8 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_log_entry_Sse(
    RustStreamSink<BridgeLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attendance_data(
    AttendanceData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_attendance_record(
    AttendanceRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vtop_config(
    VtopConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_log_entry(
    BridgeLogEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_log_level(
    BridgeLogLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_course_class_entry(
    CourseClassEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_course_info(CourseInfo self, SseSerializer serializer);

  @protected
  void sse_encode_course_option(CourseOption self, SseSerializer serializer);

  @protected
  void sse_encode_course_page_detail(
    CoursePageDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_courses_response(
    CoursesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exam_schedule_data(
    ExamScheduleData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exam_schedule_record(
    ExamScheduleRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_full_attendance_data(
    FullAttendanceData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_full_attendance_record(
    FullAttendanceRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_course_record(
    GradeCourseRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_detail_mark(
    GradeDetailMark self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_details_data(
    GradeDetailsData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_history_attempt(
    GradeHistoryAttempt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_history_cgpa(
    GradeHistoryCgpa self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_history_data(
    GradeHistoryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_history_record(
    GradeHistoryRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_history_student_info(
    GradeHistoryStudentInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_range(GradeRange self, SseSerializer serializer);

  @protected
  void sse_encode_grade_view_data(GradeViewData self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_lecture_entry(LectureEntry self, SseSerializer serializer);

  @protected
  void sse_encode_list_attendance_record(
    List<AttendanceRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_course_class_entry(
    List<CourseClassEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_course_option(
    List<CourseOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exam_schedule_record(
    List<ExamScheduleRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_full_attendance_record(
    List<FullAttendanceRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_course_record(
    List<GradeCourseRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_detail_mark(
    List<GradeDetailMark> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_history_attempt(
    List<GradeHistoryAttempt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_history_record(
    List<GradeHistoryRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_range(
    List<GradeRange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lecture_entry(
    List<LectureEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marks_record(
    List<MarksRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marks_record_each(
    List<MarksRecordEach> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_per_exam_schedule_record(
    List<PerExamScheduleRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reference_material(
    List<ReferenceMaterial> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semester_info(
    List<SemesterInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slot_option(
    List<SlotOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_timetable_slot(
    List<TimetableSlot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_marks_data(MarksData self, SseSerializer serializer);

  @protected
  void sse_encode_marks_record(MarksRecord self, SseSerializer serializer);

  @protected
  void sse_encode_marks_record_each(
    MarksRecordEach self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_per_exam_schedule_record(
    PerExamScheduleRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_material(
    ReferenceMaterial self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semester_data(SemesterData self, SseSerializer serializer);

  @protected
  void sse_encode_semester_info(SemesterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_slot_option(SlotOption self, SseSerializer serializer);

  @protected
  void sse_encode_slots_response(SlotsResponse self, SseSerializer serializer);

  @protected
  void sse_encode_timetable_data(TimetableData self, SseSerializer serializer);

  @protected
  void sse_encode_timetable_slot(TimetableSlot self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vtop_config(VtopConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vtop_error(VtopError self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultAttendanceData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursePageDetail(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultCoursesResponse(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultExamScheduleData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFullAttendanceData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeDetailsData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeViewData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultMarksData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSlotsResponse(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultTimetableData(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
    int ptr,
  );
}
