// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'types.freezed.dart';
part 'types.g.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FacultyOption`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class AttendanceData with _$AttendanceData {
  const factory AttendanceData({
    required List<AttendanceRecord> records,
    required String semesterId,
    required BigInt updateTime,
  }) = _AttendanceData;

  factory AttendanceData.fromJson(Map<String, dynamic> json) =>
      _$AttendanceDataFromJson(json);
}

@freezed
@meta.immutable
sealed class AttendanceRecord with _$AttendanceRecord {
  const factory AttendanceRecord({
    required String serial,
    required String category,
    required String courseName,
    required String courseCode,
    required String courseType,
    required String facultyDetail,
    required String classesAttended,
    required String totalClasses,
    required String attendancePercentage,
    required String attendenceFatCat,
    required String debarStatus,
    required String courseId,
  }) = _AttendanceRecord;

  factory AttendanceRecord.fromJson(Map<String, dynamic> json) =>
      _$AttendanceRecordFromJson(json);
}

/// Represents a class entry in the course slots table
@freezed
@meta.immutable
sealed class CourseClassEntry with _$CourseClassEntry {
  const factory CourseClassEntry({
    required int slNo,
    required String classGroup,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String classId,
    required String slot,
    required String faculty,
    required String semesterId,
    required String erpId,
  }) = _CourseClassEntry;

  factory CourseClassEntry.fromJson(Map<String, dynamic> json) =>
      _$CourseClassEntryFromJson(json);
}

/// Represents course information in the detail view
@freezed
@meta.immutable
sealed class CourseInfo with _$CourseInfo {
  const factory CourseInfo({
    required String classGroup,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String classId,
    required String slot,
    required String faculty,
    required String courseId,
  }) = _CourseInfo;

  factory CourseInfo.fromJson(Map<String, dynamic> json) =>
      _$CourseInfoFromJson(json);
}

/// Represents a course option available in the course page dropdown
@freezed
@meta.immutable
sealed class CourseOption with _$CourseOption {
  const factory CourseOption({
    required String value,
    required String label,
    required String courseCode,
    required String courseTitle,
    required String courseType,
  }) = _CourseOption;

  factory CourseOption.fromJson(Map<String, dynamic> json) =>
      _$CourseOptionFromJson(json);
}

/// Represents the detailed course page with all materials
@freezed
@meta.immutable
sealed class CoursePageDetail with _$CoursePageDetail {
  const factory CoursePageDetail({
    required CourseInfo courseInfo,
    required String semesterId,
    String? downloadAllPath,
    String? downloadGeneralMaterialsPath,
    String? syllabusDownloadPath,
    String? coursePlanDownloadPath,
    required List<LectureEntry> lectures,
  }) = _CoursePageDetail;

  factory CoursePageDetail.fromJson(Map<String, dynamic> json) =>
      _$CoursePageDetailFromJson(json);
}

/// Response for getting courses for a semester
@freezed
@meta.immutable
sealed class CoursesResponse with _$CoursesResponse {
  const factory CoursesResponse({required List<CourseOption> courses}) =
      _CoursesResponse;

  factory CoursesResponse.fromJson(Map<String, dynamic> json) =>
      _$CoursesResponseFromJson(json);
}

@freezed
@meta.immutable
sealed class ExamScheduleData with _$ExamScheduleData {
  const factory ExamScheduleData({
    required List<PerExamScheduleRecord> exams,
    required String semesterId,
    required BigInt updateTime,
  }) = _ExamScheduleData;

  factory ExamScheduleData.fromJson(Map<String, dynamic> json) =>
      _$ExamScheduleDataFromJson(json);
}

@freezed
@meta.immutable
sealed class ExamScheduleRecord with _$ExamScheduleRecord {
  const factory ExamScheduleRecord({
    required String serial,
    required String slot,
    required String courseName,
    required String courseCode,
    required String courseType,
    required String courseId,
    required String examDate,
    required String examSession,
    required String reportingTime,
    required String examTime,
    required String venue,
    required String seatLocation,
    required String seatNo,
  }) = _ExamScheduleRecord;

  factory ExamScheduleRecord.fromJson(Map<String, dynamic> json) =>
      _$ExamScheduleRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class FullAttendanceData with _$FullAttendanceData {
  const factory FullAttendanceData({
    required List<FullAttendanceRecord> records,
    required String semesterId,
    required BigInt updateTime,
    required String courseId,
    required String courseType,
  }) = _FullAttendanceData;

  factory FullAttendanceData.fromJson(Map<String, dynamic> json) =>
      _$FullAttendanceDataFromJson(json);
}

@freezed
@meta.immutable
sealed class FullAttendanceRecord with _$FullAttendanceRecord {
  const factory FullAttendanceRecord({
    required String serial,
    required String date,
    required String slot,
    required String dayTime,
    required String status,
    required String remark,
  }) = _FullAttendanceRecord;

  factory FullAttendanceRecord.fromJson(Map<String, dynamic> json) =>
      _$FullAttendanceRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeCourseRecord with _$GradeCourseRecord {
  const factory GradeCourseRecord({
    required String serial,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String gradingType,
    required String grandTotal,
    required String grade,
    required String courseId,
  }) = _GradeCourseRecord;

  factory GradeCourseRecord.fromJson(Map<String, dynamic> json) =>
      _$GradeCourseRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeDetailMark with _$GradeDetailMark {
  const factory GradeDetailMark({
    required String serial,
    required String markTitle,
    required String maxMark,
    required String weightage,
    required String status,
    required String scoredMark,
    required String weightageMark,
  }) = _GradeDetailMark;

  factory GradeDetailMark.fromJson(Map<String, dynamic> json) =>
      _$GradeDetailMarkFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeDetailsData with _$GradeDetailsData {
  const factory GradeDetailsData({
    required String semesterId,
    required String courseId,
    required String classNumber,
    required String classCourseType,
    required String grandTotal,
    required List<GradeDetailMark> marks,
    required List<GradeRange> gradeRanges,
    required BigInt updateTime,
  }) = _GradeDetailsData;

  factory GradeDetailsData.fromJson(Map<String, dynamic> json) =>
      _$GradeDetailsDataFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeHistoryAttempt with _$GradeHistoryAttempt {
  const factory GradeHistoryAttempt({
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String credits,
    required String grade,
    required String examMonth,
    required String resultDeclared,
  }) = _GradeHistoryAttempt;

  factory GradeHistoryAttempt.fromJson(Map<String, dynamic> json) =>
      _$GradeHistoryAttemptFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeHistoryCgpa with _$GradeHistoryCgpa {
  const factory GradeHistoryCgpa({
    required String creditsRegistered,
    required String creditsEarned,
    required String cgpa,
    required String sGrades,
    required String aGrades,
    required String bGrades,
    required String cGrades,
    required String dGrades,
    required String eGrades,
    required String fGrades,
    required String nGrades,
  }) = _GradeHistoryCgpa;

  factory GradeHistoryCgpa.fromJson(Map<String, dynamic> json) =>
      _$GradeHistoryCgpaFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeHistoryData with _$GradeHistoryData {
  const factory GradeHistoryData({
    required GradeHistoryStudentInfo student,
    required List<GradeHistoryRecord> records,
    required GradeHistoryCgpa cgpa,
    required BigInt updateTime,
  }) = _GradeHistoryData;

  factory GradeHistoryData.fromJson(Map<String, dynamic> json) =>
      _$GradeHistoryDataFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeHistoryRecord with _$GradeHistoryRecord {
  const factory GradeHistoryRecord({
    required String serial,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String credits,
    required String grade,
    required String examMonth,
    required String resultDeclared,
    required String courseDistribution,
    required List<GradeHistoryAttempt> attempts,
  }) = _GradeHistoryRecord;

  factory GradeHistoryRecord.fromJson(Map<String, dynamic> json) =>
      _$GradeHistoryRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeHistoryStudentInfo with _$GradeHistoryStudentInfo {
  const factory GradeHistoryStudentInfo({
    required String regNo,
    required String name,
    required String programmeBranch,
    required String programmeMode,
    required String studySystem,
    required String gender,
    required String yearJoined,
    required String eduStatus,
    required String school,
    required String campus,
  }) = _GradeHistoryStudentInfo;

  factory GradeHistoryStudentInfo.fromJson(Map<String, dynamic> json) =>
      _$GradeHistoryStudentInfoFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeRange with _$GradeRange {
  const factory GradeRange({required String grade, required String range}) =
      _GradeRange;

  factory GradeRange.fromJson(Map<String, dynamic> json) =>
      _$GradeRangeFromJson(json);
}

@freezed
@meta.immutable
sealed class GradeViewData with _$GradeViewData {
  const factory GradeViewData({
    required List<GradeCourseRecord> courses,
    required List<SemesterInfo> semesters,
    required String semesterId,
    required BigInt updateTime,
  }) = _GradeViewData;

  factory GradeViewData.fromJson(Map<String, dynamic> json) =>
      _$GradeViewDataFromJson(json);
}

/// Represents a lecture entry in the course detail page
@freezed
@meta.immutable
sealed class LectureEntry with _$LectureEntry {
  const factory LectureEntry({
    required int slNo,
    required String date,
    required String formattedDate,
    required String day,
    required String topic,
    required List<ReferenceMaterial> referenceMaterials,
  }) = _LectureEntry;

  factory LectureEntry.fromJson(Map<String, dynamic> json) =>
      _$LectureEntryFromJson(json);
}

@freezed
@meta.immutable
sealed class MarksData with _$MarksData {
  const factory MarksData({
    required List<MarksRecord> records,
    required String semesterId,
    required BigInt updateTime,
  }) = _MarksData;

  factory MarksData.fromJson(Map<String, dynamic> json) =>
      _$MarksDataFromJson(json);
}

@freezed
@meta.immutable
sealed class MarksRecord with _$MarksRecord {
  const factory MarksRecord({
    required String serial,
    required String coursecode,
    required String coursetitle,
    required String coursetype,
    required String faculity,
    required String slot,
    required List<MarksRecordEach> marks,
  }) = _MarksRecord;

  factory MarksRecord.fromJson(Map<String, dynamic> json) =>
      _$MarksRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class MarksRecordEach with _$MarksRecordEach {
  const factory MarksRecordEach({
    required String serial,
    required String markstitle,
    required String maxmarks,
    required String weightage,
    required String status,
    required String scoredmark,
    required String weightagemark,
    required String remark,
  }) = _MarksRecordEach;

  factory MarksRecordEach.fromJson(Map<String, dynamic> json) =>
      _$MarksRecordEachFromJson(json);
}

@freezed
@meta.immutable
sealed class PerExamScheduleRecord with _$PerExamScheduleRecord {
  const factory PerExamScheduleRecord({
    required List<ExamScheduleRecord> records,
    required String examType,
  }) = _PerExamScheduleRecord;

  factory PerExamScheduleRecord.fromJson(Map<String, dynamic> json) =>
      _$PerExamScheduleRecordFromJson(json);
}

/// Represents a reference material attached to a lecture
@freezed
@meta.immutable
sealed class ReferenceMaterial with _$ReferenceMaterial {
  const factory ReferenceMaterial({
    required String label,
    required String downloadPath,
  }) = _ReferenceMaterial;

  factory ReferenceMaterial.fromJson(Map<String, dynamic> json) =>
      _$ReferenceMaterialFromJson(json);
}

@freezed
@meta.immutable
sealed class SemesterData with _$SemesterData {
  const factory SemesterData({
    required List<SemesterInfo> semesters,
    required BigInt updateTime,
  }) = _SemesterData;

  factory SemesterData.fromJson(Map<String, dynamic> json) =>
      _$SemesterDataFromJson(json);
}

@freezed
@meta.immutable
sealed class SemesterInfo with _$SemesterInfo {
  const factory SemesterInfo({required String id, required String name}) =
      _SemesterInfo;

  factory SemesterInfo.fromJson(Map<String, dynamic> json) =>
      _$SemesterInfoFromJson(json);
}

/// Represents a slot option for a course
@freezed
@meta.immutable
sealed class SlotOption with _$SlotOption {
  const factory SlotOption({required String value, required String label}) =
      _SlotOption;

  factory SlotOption.fromJson(Map<String, dynamic> json) =>
      _$SlotOptionFromJson(json);
}

/// Response for getting slots for a course
@freezed
@meta.immutable
sealed class SlotsResponse with _$SlotsResponse {
  const factory SlotsResponse({
    required List<SlotOption> slots,
    required List<CourseClassEntry> classEntries,
  }) = _SlotsResponse;

  factory SlotsResponse.fromJson(Map<String, dynamic> json) =>
      _$SlotsResponseFromJson(json);
}

@freezed
@meta.immutable
sealed class TimetableData with _$TimetableData {
  const factory TimetableData({
    required List<TimetableSlot> slots,
    required String semesterId,
    required BigInt updateTime,
  }) = _TimetableData;

  factory TimetableData.fromJson(Map<String, dynamic> json) =>
      _$TimetableDataFromJson(json);
}

@freezed
@meta.immutable
sealed class TimetableSlot with _$TimetableSlot {
  const factory TimetableSlot({
    required String serial,
    required String day,
    required String slot,
    required String courseCode,
    required String courseType,
    required String roomNo,
    required String block,
    required String startTime,
    required String endTime,
    required String name,
    required bool isLab,
    required String faculty,
  }) = _TimetableSlot;

  factory TimetableSlot.fromJson(Map<String, dynamic> json) =>
      _$TimetableSlotFromJson(json);
}
