// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session_manager.dart';
import 'vtop_config.dart';

// These functions are ignored because they are not marked as `pub`: `extract_captcha_data`, `extract_csrf_token`, `get_csrf_for_cookie_set`, `get_regno`, `load_initial_page`, `load_login_page`, `make_client`, `perform_login`, `reqwest_network_error`, `solve_captcha`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopClient>>
abstract class VtopClient implements RustOpaqueInterface {
  Future<VtopResultVecU8> downloadCourseMaterial({
    required String downloadPath,
  });

  Future<VtopResultVecU8> downloadCourseSyllabus({
    required String courseId,
    required String courseType,
  });

  Future<VtopResultAttendanceData> getAttendance({required String semesterId});

  Future<VtopResultVecU8> getCookie({required bool check});

  Future<VtopResultCoursePageDetail> getCourseDetail({
    required String semesterId,
    required String erpId,
    required String classId,
  });

  Future<VtopResultCoursesResponse> getCoursesForCoursePage({
    required bool check,
  });

  Future<VtopResultExamScheduleData> getExamSchedule({
    required String semesterId,
  });

  Future<VtopResultFullAttendanceData> getFullAttendance({
    required String semesterId,
    required String courseId,
    required String courseType,
  });

  Future<VtopResultGradeHistoryData> getGradeHistory();

  Future<VtopResultGradeViewData> getGradeView({required String semesterId});

  Future<VtopResultGradeDetailsData> getGradeViewDetails({
    required String semesterId,
    required String courseId,
  });

  Future<VtopResultMarksData> getMarks({required String semesterId});

  Future<VtopResultSemesterData> getSemesters({required bool check});

  Future<VtopResultSlotsResponse> getSlotsForCoursePage({
    required String semesterId,
    required String courseId,
  });

  Future<VtopResultTimetableData> getTimetable({required String semesterId});

  Future<bool> isAuthenticated();

  Future<VtopResult> login();

  Future<void> setCookie({required String cookie});

  static Future<VtopClient> withConfig({
    required VtopConfig config,
    required SessionManager session,
    required String username,
    required String password,
  }) => RustLib.instance.api.crateApiVtopVtopClientVtopClientWithConfig(
    config: config,
    session: session,
    username: username,
    password: password,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < () >>>
abstract class VtopResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < AttendanceData >>>
abstract class VtopResultAttendanceData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < CoursePageDetail >>>
abstract class VtopResultCoursePageDetail implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < CoursesResponse >>>
abstract class VtopResultCoursesResponse implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < ExamScheduleData >>>
abstract class VtopResultExamScheduleData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < FullAttendanceData >>>
abstract class VtopResultFullAttendanceData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GradeDetailsData >>>
abstract class VtopResultGradeDetailsData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GradeHistoryData >>>
abstract class VtopResultGradeHistoryData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GradeViewData >>>
abstract class VtopResultGradeViewData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < MarksData >>>
abstract class VtopResultMarksData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < SemesterData >>>
abstract class VtopResultSemesterData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < SlotsResponse >>>
abstract class VtopResultSlotsResponse implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < TimetableData >>>
abstract class VtopResultTimetableData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < u8 > >>>
abstract class VtopResultVecU8 implements RustOpaqueInterface {}
