// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_log`, `log_debug`, `log_error`, `log_info`, `log_warn`, `now_millis`, `sink_cell`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Stream<BridgeLogEntry> createLogStream() =>
    RustLib.instance.api.crateApiLoggingCreateLogStream();

class BridgeLogEntry {
  final BridgeLogLevel level;
  final String source;
  final String message;
  final BigInt timestampMillis;

  const BridgeLogEntry({
    required this.level,
    required this.source,
    required this.message,
    required this.timestampMillis,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      source.hashCode ^
      message.hashCode ^
      timestampMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLogEntry &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          source == other.source &&
          message == other.message &&
          timestampMillis == other.timestampMillis;
}

enum BridgeLogLevel { trace, debug, info, warn, error }
